name: '$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)'

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: build
    jobs:
    - job: Applications_2020
      steps:
        - template: apps.yml      
          parameters:
            version: 2020    

    - job: Applications_2019i
      steps:
        - template: apps.yml      
          parameters:
            version: 2019i

    - job: Applications_2019
      steps:
        - template: apps.yml      
          parameters:
            version: 2019            

    - job: Applications_2018
      steps:
        - template: apps.yml      
          parameters:
            version: 2018           

    - job: Plugins
      steps:
        - template: plugins.yml